/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FmrlLinkInput {
        "base": string;
        "button": string;
        "defaultValue": string;
        "label": string;
        "placeholder": string;
        "protocol": string;
        "target": string;
        "transform": 'lower' | 'upper' | 'none';
    }
    interface FmrlOtpEncrypt {
    }
    interface FmrlRedeemInstructionsAmazon {
    }
    interface FmrlRedeemInstructionsApple {
    }
    interface FmrlRedeemInstructionsMastercard {
    }
    interface FmrlScramble {
        "data": string;
        "dataSrc": string;
        "delay": number;
        "repeat": number;
    }
    interface FmrlScrambleText {
        "heading": 1 | 2 | 3 | 4 | 5 | 6;
        "startText": string;
        "text": string;
    }
    interface FmrlVoucher {
        "amount": string;
        "code": string;
        "encrypted": boolean;
        "hint": string;
        "link": string;
        "type": 'amazon' | 'apple' | 'mastercard' | 'other';
    }
}
declare global {
    interface HTMLFmrlLinkInputElement extends Components.FmrlLinkInput, HTMLStencilElement {
    }
    var HTMLFmrlLinkInputElement: {
        prototype: HTMLFmrlLinkInputElement;
        new (): HTMLFmrlLinkInputElement;
    };
    interface HTMLFmrlOtpEncryptElement extends Components.FmrlOtpEncrypt, HTMLStencilElement {
    }
    var HTMLFmrlOtpEncryptElement: {
        prototype: HTMLFmrlOtpEncryptElement;
        new (): HTMLFmrlOtpEncryptElement;
    };
    interface HTMLFmrlRedeemInstructionsAmazonElement extends Components.FmrlRedeemInstructionsAmazon, HTMLStencilElement {
    }
    var HTMLFmrlRedeemInstructionsAmazonElement: {
        prototype: HTMLFmrlRedeemInstructionsAmazonElement;
        new (): HTMLFmrlRedeemInstructionsAmazonElement;
    };
    interface HTMLFmrlRedeemInstructionsAppleElement extends Components.FmrlRedeemInstructionsApple, HTMLStencilElement {
    }
    var HTMLFmrlRedeemInstructionsAppleElement: {
        prototype: HTMLFmrlRedeemInstructionsAppleElement;
        new (): HTMLFmrlRedeemInstructionsAppleElement;
    };
    interface HTMLFmrlRedeemInstructionsMastercardElement extends Components.FmrlRedeemInstructionsMastercard, HTMLStencilElement {
    }
    var HTMLFmrlRedeemInstructionsMastercardElement: {
        prototype: HTMLFmrlRedeemInstructionsMastercardElement;
        new (): HTMLFmrlRedeemInstructionsMastercardElement;
    };
    interface HTMLFmrlScrambleElement extends Components.FmrlScramble, HTMLStencilElement {
    }
    var HTMLFmrlScrambleElement: {
        prototype: HTMLFmrlScrambleElement;
        new (): HTMLFmrlScrambleElement;
    };
    interface HTMLFmrlScrambleTextElement extends Components.FmrlScrambleText, HTMLStencilElement {
    }
    var HTMLFmrlScrambleTextElement: {
        prototype: HTMLFmrlScrambleTextElement;
        new (): HTMLFmrlScrambleTextElement;
    };
    interface HTMLFmrlVoucherElement extends Components.FmrlVoucher, HTMLStencilElement {
    }
    var HTMLFmrlVoucherElement: {
        prototype: HTMLFmrlVoucherElement;
        new (): HTMLFmrlVoucherElement;
    };
    interface HTMLElementTagNameMap {
        "fmrl-link-input": HTMLFmrlLinkInputElement;
        "fmrl-otp-encrypt": HTMLFmrlOtpEncryptElement;
        "fmrl-redeem-instructions-amazon": HTMLFmrlRedeemInstructionsAmazonElement;
        "fmrl-redeem-instructions-apple": HTMLFmrlRedeemInstructionsAppleElement;
        "fmrl-redeem-instructions-mastercard": HTMLFmrlRedeemInstructionsMastercardElement;
        "fmrl-scramble": HTMLFmrlScrambleElement;
        "fmrl-scramble-text": HTMLFmrlScrambleTextElement;
        "fmrl-voucher": HTMLFmrlVoucherElement;
    }
}
declare namespace LocalJSX {
    interface FmrlLinkInput {
        "base"?: string;
        "button"?: string;
        "defaultValue"?: string;
        "label"?: string;
        "placeholder"?: string;
        "protocol"?: string;
        "target"?: string;
        "transform"?: 'lower' | 'upper' | 'none';
    }
    interface FmrlOtpEncrypt {
    }
    interface FmrlRedeemInstructionsAmazon {
    }
    interface FmrlRedeemInstructionsApple {
    }
    interface FmrlRedeemInstructionsMastercard {
    }
    interface FmrlScramble {
        "data"?: string;
        "dataSrc"?: string;
        "delay"?: number;
        "repeat"?: number;
    }
    interface FmrlScrambleText {
        "heading"?: 1 | 2 | 3 | 4 | 5 | 6;
        "onScrambleDone"?: (event: CustomEvent<any>) => void;
        "startText"?: string;
        "text"?: string;
    }
    interface FmrlVoucher {
        "amount"?: string;
        "code"?: string;
        "encrypted"?: boolean;
        "hint"?: string;
        "link"?: string;
        "type"?: 'amazon' | 'apple' | 'mastercard' | 'other';
    }
    interface IntrinsicElements {
        "fmrl-link-input": FmrlLinkInput;
        "fmrl-otp-encrypt": FmrlOtpEncrypt;
        "fmrl-redeem-instructions-amazon": FmrlRedeemInstructionsAmazon;
        "fmrl-redeem-instructions-apple": FmrlRedeemInstructionsApple;
        "fmrl-redeem-instructions-mastercard": FmrlRedeemInstructionsMastercard;
        "fmrl-scramble": FmrlScramble;
        "fmrl-scramble-text": FmrlScrambleText;
        "fmrl-voucher": FmrlVoucher;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "fmrl-link-input": LocalJSX.FmrlLinkInput & JSXBase.HTMLAttributes<HTMLFmrlLinkInputElement>;
            "fmrl-otp-encrypt": LocalJSX.FmrlOtpEncrypt & JSXBase.HTMLAttributes<HTMLFmrlOtpEncryptElement>;
            "fmrl-redeem-instructions-amazon": LocalJSX.FmrlRedeemInstructionsAmazon & JSXBase.HTMLAttributes<HTMLFmrlRedeemInstructionsAmazonElement>;
            "fmrl-redeem-instructions-apple": LocalJSX.FmrlRedeemInstructionsApple & JSXBase.HTMLAttributes<HTMLFmrlRedeemInstructionsAppleElement>;
            "fmrl-redeem-instructions-mastercard": LocalJSX.FmrlRedeemInstructionsMastercard & JSXBase.HTMLAttributes<HTMLFmrlRedeemInstructionsMastercardElement>;
            "fmrl-scramble": LocalJSX.FmrlScramble & JSXBase.HTMLAttributes<HTMLFmrlScrambleElement>;
            "fmrl-scramble-text": LocalJSX.FmrlScrambleText & JSXBase.HTMLAttributes<HTMLFmrlScrambleTextElement>;
            "fmrl-voucher": LocalJSX.FmrlVoucher & JSXBase.HTMLAttributes<HTMLFmrlVoucherElement>;
        }
    }
}
