/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FmrlLinkInput {
        "base": string;
        "button": string;
        "defaultValue": string;
        "label": string;
        "placeholder": string;
        "protocol": string;
        "target": string;
        "transform": 'lower' | 'upper' | 'none';
    }
    interface FmrlScramble {
        "data": string;
        "dataSrc": string;
        "delay": number;
        "repeat": number;
    }
    interface FmrlScrambleText {
        "heading": 1 | 2 | 3 | 4 | 5 | 6;
        "text": string;
    }
    interface FmrlVoucher {
    }
}
declare global {
    interface HTMLFmrlLinkInputElement extends Components.FmrlLinkInput, HTMLStencilElement {
    }
    var HTMLFmrlLinkInputElement: {
        prototype: HTMLFmrlLinkInputElement;
        new (): HTMLFmrlLinkInputElement;
    };
    interface HTMLFmrlScrambleElement extends Components.FmrlScramble, HTMLStencilElement {
    }
    var HTMLFmrlScrambleElement: {
        prototype: HTMLFmrlScrambleElement;
        new (): HTMLFmrlScrambleElement;
    };
    interface HTMLFmrlScrambleTextElement extends Components.FmrlScrambleText, HTMLStencilElement {
    }
    var HTMLFmrlScrambleTextElement: {
        prototype: HTMLFmrlScrambleTextElement;
        new (): HTMLFmrlScrambleTextElement;
    };
    interface HTMLFmrlVoucherElement extends Components.FmrlVoucher, HTMLStencilElement {
    }
    var HTMLFmrlVoucherElement: {
        prototype: HTMLFmrlVoucherElement;
        new (): HTMLFmrlVoucherElement;
    };
    interface HTMLElementTagNameMap {
        "fmrl-link-input": HTMLFmrlLinkInputElement;
        "fmrl-scramble": HTMLFmrlScrambleElement;
        "fmrl-scramble-text": HTMLFmrlScrambleTextElement;
        "fmrl-voucher": HTMLFmrlVoucherElement;
    }
}
declare namespace LocalJSX {
    interface FmrlLinkInput {
        "base"?: string;
        "button"?: string;
        "defaultValue"?: string;
        "label"?: string;
        "placeholder"?: string;
        "protocol"?: string;
        "target"?: string;
        "transform"?: 'lower' | 'upper' | 'none';
    }
    interface FmrlScramble {
        "data"?: string;
        "dataSrc"?: string;
        "delay"?: number;
        "repeat"?: number;
    }
    interface FmrlScrambleText {
        "heading"?: 1 | 2 | 3 | 4 | 5 | 6;
        "onScrambleDone"?: (event: CustomEvent<any>) => void;
        "text"?: string;
    }
    interface FmrlVoucher {
    }
    interface IntrinsicElements {
        "fmrl-link-input": FmrlLinkInput;
        "fmrl-scramble": FmrlScramble;
        "fmrl-scramble-text": FmrlScrambleText;
        "fmrl-voucher": FmrlVoucher;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "fmrl-link-input": LocalJSX.FmrlLinkInput & JSXBase.HTMLAttributes<HTMLFmrlLinkInputElement>;
            "fmrl-scramble": LocalJSX.FmrlScramble & JSXBase.HTMLAttributes<HTMLFmrlScrambleElement>;
            "fmrl-scramble-text": LocalJSX.FmrlScrambleText & JSXBase.HTMLAttributes<HTMLFmrlScrambleTextElement>;
            "fmrl-voucher": LocalJSX.FmrlVoucher & JSXBase.HTMLAttributes<HTMLFmrlVoucherElement>;
        }
    }
}
